### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'the'

### ISSUE THREAD

**Issue by SeekPoint** [Irvinglove/TF_Sentence_Similarity_CNN#2]
python train.py 

Parameters:
ALLOW_SOFT_PLACEMENT=True
BATCH_SIZE=64
CHECKPOINT_EVERY=100
DATA_FILE=SICK_data/SICK.txt
DROPOUT_KEEP_PROB=0.5
EVALUATE_EVERY=100
FILTER_SIZES=3,4,5
L2_REG_LAMBDA=1
LOG_DEVICE_PLACEMENT=False
NUM_CHECKPOINTS=5
NUM_CLASSES=1
NUM_EPOCHS=200
NUM_FILTERS=128
SEQ_LENGTH=36
TRAIN_SAMPLE_PERCENTAGE=0.9

Loading data...
Traceback (most recent call last):
  File "train.py", line 52, in <module>
    s1 ,s2, score = data_helper.read_data_sets(FLAGS.data_file)
  File "//paraphrase-id-tensorflow/TF_Sentence_Similarity_CNN/data_helper.py", line 105, in read_data_sets
    sr_word2id, word_embedding = build_glove_dic()
  File "//paraphrase-id-tensorflow/TF_Sentence_Similarity_CNN/data_helper.py", line 130, in build_glove_dic
    wv = word2vec.load(glove_path)
  File "/Library/Python/2.7/site-packages/word2vec/io.py", line 20, in load
    return word2vec.WordVectors.from_text(fname, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/word2vec/wordvectors.py", line 234, in from_text
    vocab_size, vector_size = list(map(int, header.split()))
ValueError: invalid literal for int() with base 10: 'the'

**Comment by Irvinglove** [comment]
You should add

400000 50

at the first row in the glove.6B.50d.txt file,  after that we could read the glove with word2vec tools.

I'm sorry that I had not added this note in the README.md. Now I have changed it.

**Comment by SeekPoint** [comment]
after take your suggestion

python train.py 

Parameters:
ALLOW_SOFT_PLACEMENT=True
BATCH_SIZE=64
CHECKPOINT_EVERY=100
DATA_FILE=SICK_data/SICK.txt
DROPOUT_KEEP_PROB=0.5
EVALUATE_EVERY=100
FILTER_SIZES=3,4,5
L2_REG_LAMBDA=1
LOG_DEVICE_PLACEMENT=False
NUM_CHECKPOINTS=5
NUM_CLASSES=1
NUM_EPOCHS=200
NUM_FILTERS=128
SEQ_LENGTH=36
TRAIN_SAMPLE_PERCENTAGE=0.9

Loading data...
Traceback (most recent call last):
  File "train.py", line 52, in <module>
    s1 ,s2, score = data_helper.read_data_sets(FLAGS.data_file)
  File "/Users//TF_Sentence_Similarity_CNN/data_helper.py", line 105, in read_data_sets
    sr_word2id, word_embedding = build_glove_dic()
  File "/Users//TF_Sentence_Similarity_CNN/data_helper.py", line 130, in build_glove_dic
    wv = word2vec.load(glove_path)
  File "/Library/Python/2.7/site-packages/word2vec/io.py", line 20, in load
    return word2vec.WordVectors.from_text(fname, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/word2vec/wordvectors.py", line 245, in from_text
    vocab[i] = word
IndexError: index 400000 is out of bounds for axis 0 with size 400000

**Comment by Irvinglove** [comment]
You need to re-download the glove file from the [official website](https://nlp.stanford.edu/projects/glove/). OR，
delete the last line of the original document downloaded from baiduyun.

**Comment by SeekPoint** [comment]
it works now
